# Generated by Django 4.2.4 on 2023-08-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[],
        ),
    ]
