# Generated by Django 4.2.4 on 2023-08-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_account_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[],
        ),
    ]
