# Generated by Django 4.2.4 on 2023-08-18 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MF_SIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("last_date", models.DateField()),
                ("next_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "MF",
            },
        ),
        migrations.CreateModel(
            name="MF_LUMSUM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "MF_LUMSUM",
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_invest", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "invested_this_year",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("year", models.IntegerField(default=2023)),
                ("done", models.BooleanField(default=False)),
                ("risky", models.IntegerField(max_length=2)),
                ("safe", models.IntegerField(max_length=2)),
                ("MF", models.IntegerField(max_length=20)),
                ("SmallCase", models.IntegerField(max_length=20)),
                ("trade", models.IntegerField(default=0, max_length=20)),
                ("large", models.IntegerField(max_length=20)),
                ("mid", models.IntegerField(max_length=20)),
                ("small", models.IntegerField(max_length=20)),
                ("FD", models.IntegerField(max_length=20)),
                ("SGB", models.IntegerField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Investment",
            },
        ),
    ]
