# Generated by Django 4.2.4 on 2023-08-18 11:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Investments", "0002_alter_investment_fd_alter_investment_mf_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MF_SIP",
            new_name="MF",
        ),
        migrations.AlterModelOptions(
            name="mf",
            options={
                "verbose_name": "Mutual Fund",
                "verbose_name_plural": "Mutual Fund",
            },
        ),
        migrations.DeleteModel(
            name="MF_LUMSUM",
        ),
    ]
