# Generated by Django 4.2.4 on 2023-08-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Investments", "0003_rename_mf_sip_mf_alter_mf_options_delete_mf_lumsum"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="FD_i",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="investment",
            name="MF_i",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="investment",
            name="SGB_i",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="investment",
            name="SmallCase_i",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="investment",
            name="large_i",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="investment",
            name="mid_i",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="investment",
            name="small_i",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="investment",
            name="trade_i",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="mf",
            name="is_sip",
            field=models.BooleanField(default=False),
        ),
    ]
