# Generated by Django 4.2.4 on 2023-08-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Investments", "0005_mfdata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mfdata",
            name="returns",
        ),
        migrations.AddField(
            model_name="mfdata",
            name="d1",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="mfdata",
            name="d2",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="mfdata",
            name="d3",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="mfdata",
            name="d4",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="mfdata",
            name="d5",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="mfdata",
            name="dmax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="mfdata",
            name="dmin",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
