# Generated by Django 4.2.4 on 2023-08-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Investments",
            "0006_remove_mfdata_returns_mfdata_d1_mfdata_d2_mfdata_d3_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mfdata",
            options={
                "verbose_name": "Mutual Fund Data",
                "verbose_name_plural": "Mutual Fund Data",
            },
        ),
        migrations.AddField(
            model_name="mf",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="mf",
            name="next_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
