# Generated by Django 4.2.4 on 2023-08-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Investments", "0007_alter_mfdata_options_mf_quantity_alter_mf_next_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="mfdata",
            name="prev_return",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="mfdata",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
