# Generated by Django 4.2.4 on 2023-08-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Investments", "0008_mfdata_prev_return_mfdata_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="mf",
            name="sold",
            field=models.BooleanField(default=False),
        ),
    ]
