# Generated by Django 4.2.4 on 2023-08-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Investments", "0009_mf_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mfdata",
            name="prev_return",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mfdata",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
    ]
