# Generated by Django 4.2.4 on 2023-08-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Investments", "0010_alter_mfdata_prev_return_alter_mfdata_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=100)),
                ("isNIFTY50", models.BooleanField(default=False)),
                ("isNIFTY100", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[("l", "l"), ("m", "m"), ("s", "s")], max_length=100
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("ESG", models.IntegerField(default=0)),
                (
                    "ma50",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "ma200",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("pe", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("pb", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                (
                    "roe",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "doe",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "enterpriseToEbitda",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "week52low",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "week52high",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "dividendYield",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "rsi",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "ta",
                    models.CharField(
                        choices=[
                            ("b", "b"),
                            ("s", "s"),
                            ("n", "n"),
                            ("sb", "sb"),
                            ("ss", "ss"),
                        ],
                        max_length=100,
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                ("d1", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("d2", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("d3", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("d4", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("d5", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                (
                    "dmin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "dmax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
            ],
            options={
                "verbose_name": "Stock Data",
                "verbose_name_plural": "Stock Data",
            },
        ),
    ]
