# Generated by Django 4.2.4 on 2023-08-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Investments", "0012_remove_stockdata_d1_remove_stockdata_d2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockdata",
            name="isNIFTY100",
        ),
        migrations.RemoveField(
            model_name="stockdata",
            name="isNIFTY50",
        ),
        migrations.AddField(
            model_name="stockdata",
            name="nifty50",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="niftyauto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="niftybank",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="niftyenergy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="niftyfmcg",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="niftyhealthcare",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="niftyit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="niftynext50",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="niftypharma",
            field=models.BooleanField(default=False),
        ),
    ]
