# Generated by Django 4.2.4 on 2023-08-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Investments", "0013_remove_stockdata_isnifty100_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdata",
            name="buysignal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="ta",
            field=models.CharField(
                choices=[
                    ("b", "b"),
                    ("s", "s"),
                    ("n", "n"),
                    ("sb", "sb"),
                    ("ss", "ss"),
                ],
                default="n",
                max_length=100,
            ),
        ),
    ]
