# Generated by Django 4.2.4 on 2023-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Investments", "0015_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="sell_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
    ]
