# Generated by Django 4.2.4 on 2023-08-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Investments", "0019_other"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investment",
            name="SmallCase",
        ),
        migrations.RemoveField(
            model_name="investment",
            name="SmallCase_i",
        ),
        migrations.RemoveField(
            model_name="investment",
            name="trade",
        ),
        migrations.RemoveField(
            model_name="investment",
            name="trade_i",
        ),
    ]
