# Generated by Django 4.2.4 on 2023-08-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Investments", "0021_alter_other_options_alter_other_category_sgb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sgb",
            old_name="buy_date",
            new_name="date",
        ),
    ]
