# Generated by Django 4.2.4 on 2023-08-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Investments", "0022_rename_buy_date_sgb_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sgb",
            options={"verbose_name": "SGB", "verbose_name_plural": "SGB"},
        ),
        migrations.AlterField(
            model_name="investment",
            name="to_invest",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
