# Generated by Django 4.2.4 on 2023-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="expense",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="balance",
            name="invest",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="balance",
            name="invest_p",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="balance",
            name="last_month",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
