# Generated by Django 4.2.4 on 2023-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0002_balance_expense_balance_invest_balance_invest_p_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balance",
            options={"verbose_name_plural": "Balance"},
        ),
        migrations.AddField(
            model_name="balance",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
