# Generated by Django 4.2.4 on 2023-08-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Yearly", "Yearly"),
                            ("Once", "Once"),
                        ],
                        default="Monthly",
                        max_length=255,
                    ),
                ),
                ("last_date", models.DateField()),
                ("next_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wants",
                "ordering": ["-last_date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_expense", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "used_this_month",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "wants",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "needs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "wants_i",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "needs_i",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expense",
                "ordering": ["-date"],
            },
        ),
    ]
