# Generated by Django 4.2.4 on 2023-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wants",
            name="description",
        ),
        migrations.AddField(
            model_name="expense",
            name="buffer",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
