# Generated by Django 4.2.4 on 2023-08-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0002_remove_wants_description_expense_buffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="wants",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
