# Generated by Django 4.2.4 on 2023-08-23 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expense", "0003_wants_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wants",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("Quaterly", "Quaterly"),
                    ("Biannually", "Biannually"),
                    ("Yearly", "Yearly"),
                    ("Once", "Once"),
                ],
                default="Monthly",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Needs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("last_date", models.DateField()),
                ("next_date", models.DateField(blank=True, null=True)),
                ("buy_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "amount_added",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Needs",
                "ordering": ["-last_date"],
            },
        ),
    ]
