# Generated by Django 4.2.4 on 2023-08-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0004_alter_wants_frequency_needs"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="buffer2",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="needs",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="needs",
            name="remarks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
