# Generated by Django 4.2.4 on 2023-08-28 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0005_expense_buffer2_needs_price_needs_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=datetime.date(2023, 8, 29)),
        ),
        migrations.AlterField(
            model_name="expense",
            name="to_expense",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="wants",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
