# Generated by Django 4.2.4 on 2023-08-10 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomeobject",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incomeobject",
            name="next_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incomeobject",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Income",
        ),
    ]
