# Generated by Django 4.2.4 on 2023-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_incomeobject_description_incomeobject_next_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomeobject",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                    ("Yearly", "Yearly"),
                    ("Once", "Once"),
                ],
                default="Monthly",
                max_length=255,
            ),
        ),
    ]
