# Generated by Django 4.2.4 on 2023-08-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0003_alter_incomeobject_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomeobject",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
