# Generated by Django 4.2.4 on 2023-08-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_incomeobject_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeobject',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
