# Generated by Django 4.2.4 on 2023-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0005_incomeobject_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomeobject",
            name="is_passive",
            field=models.BooleanField(default=False),
        ),
    ]
